import { PlaceCategory } from 'src/app/interfaces/place-category.interface';

export const allCategories: Array<PlaceCategory> = [
  { 'id': 'restaurant,food-drink' },
  { 'id': 'snacks-fast-food' },
  { 'id': 'restaurant,food-drink,snacks-fast-food' },
  { 'id': 'coffee-tea,coffee' },
  { 'id': 'dance-night-club' },
  { 'id': 'theatre-music-culture' },
  { 'id': 'casino' },
  { 'id': 'sights-museums,museum' },
  { 'id': 'camping' },
  { 'id': 'shopping,mall' },
  { 'id': 'bookshop' },
  { 'id': 'library' },
  { 'id': 'natural-geographical' },
  { 'id': 'bar-pub' },
  { 'id': 'cinema' },
  { 'id': 'landmark-attraction' },
  { 'id': 'sports-facility-venue' },
  { 'id': 'amusement-holiday-park' },
  { 'id': 'mountain-hill' },
  { 'id': 'hospital-health-care-facility,hospital' },
  { 'id': 'natural-geographical,mountain-hill' },
  { 'id': '_sunset' },
  { 'id': '_picnic' },
  // Home Options
  { 'id': '_invite-friends' },
  { 'id': '_host-party' },
  { 'id': '_watch-new-movie' },
  { 'id': '_watch-movie-marathon' },
  { 'id': '_view-old-pictures' },
  { 'id': '_cook-something-different' },
  { 'id': '_play-videogames' },
  { 'id': '_solve-jigsaw-puzzle' },
  { 'id': '_donate' },
];
